import { Badge, type BadgeTone } from './Badge'

export type PlanOrigin = 'ai_agent' | 'rule_engine' | 'doctor_direct'

const TONE_MAP: Record<PlanOrigin, BadgeTone> = {
  ai_agent: 'teal',
  rule_engine: 'amber',
  doctor_direct: 'blue',
}

const LABEL_MAP: Record<PlanOrigin, string> = {
  ai_agent: 'AI',
  rule_engine: 'Fallback',
  doctor_direct: 'Doctor',
}

export interface OriginBadgeProps {
  readonly origin: PlanOrigin
  readonly label?: string
  readonly accessibilityLabel?: string
  readonly testID?: string
}

/**
 * Pulled into a named component so plan headers can surface "who wrote this"
 * with one import. Colour coding matches ApprovalQueueCard's fallback-badge
 * expectations (see EB-C §4.2).
 */
export function OriginBadge({ origin, label, accessibilityLabel, testID }: OriginBadgeProps) {
  const resolvedLabel = label ?? LABEL_MAP[origin]
  return (
    <Badge
      label={resolvedLabel}
      tone={TONE_MAP[origin]}
      accessibilityLabel={accessibilityLabel ?? `Generated by ${resolvedLabel}`}
      testID={testID}
    />
  )
}
