/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(doctor)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/checkin` | `/checkin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/diet` | `/diet`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/notify` | `/notify`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/plan` | `/plan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/progress` | `/progress`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/supplements` | `/supplements`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/workout` | `/workout`; params?: Router.UnknownInputParams; } | { pathname: `${'/(doctor)'}/patient/[id]` | `/patient/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(doctor)'}/protocol/[id]` | `/protocol/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(doctor)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(patient)'}/checkin` | `/checkin`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(patient)'}/diet` | `/diet`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(patient)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(patient)'}/notify` | `/notify`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(patient)'}/plan` | `/plan`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(patient)'}/progress` | `/progress`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(patient)'}/supplements` | `/supplements`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(patient)'}/workout` | `/workout`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(doctor)'}/patient/[id]` | `/patient/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(doctor)'}/protocol/[id]` | `/protocol/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(doctor)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(patient)'}/checkin${`?${string}` | `#${string}` | ''}` | `/checkin${`?${string}` | `#${string}` | ''}` | `${'/(patient)'}/diet${`?${string}` | `#${string}` | ''}` | `/diet${`?${string}` | `#${string}` | ''}` | `${'/(patient)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(patient)'}/notify${`?${string}` | `#${string}` | ''}` | `/notify${`?${string}` | `#${string}` | ''}` | `${'/(patient)'}/plan${`?${string}` | `#${string}` | ''}` | `/plan${`?${string}` | `#${string}` | ''}` | `${'/(patient)'}/progress${`?${string}` | `#${string}` | ''}` | `/progress${`?${string}` | `#${string}` | ''}` | `${'/(patient)'}/supplements${`?${string}` | `#${string}` | ''}` | `/supplements${`?${string}` | `#${string}` | ''}` | `${'/(patient)'}/workout${`?${string}` | `#${string}` | ''}` | `/workout${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(doctor)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/checkin` | `/checkin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/diet` | `/diet`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/notify` | `/notify`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/plan` | `/plan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/progress` | `/progress`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/supplements` | `/supplements`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/workout` | `/workout`; params?: Router.UnknownInputParams; } | `${'/(doctor)'}/patient/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/patient/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `${'/(doctor)'}/protocol/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/protocol/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(doctor)'}/patient/[id]` | `/patient/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(doctor)'}/protocol/[id]` | `/protocol/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
